name: flexi_fonts_example
description: Example app for the flexi_fonts package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flexi_fonts:
    path: ../
  provider: ^6.0.5
  google_fonts: ^6.0.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Local fonts
  fonts:
    - family: Rabar
      fonts:
        - asset: assets/fonts/rabar.ttf
    
    - family: SarchiaAbdulrahman
      fonts:
        - asset: assets/fonts/03_Sarchia_Abdulrahman_1.ttf