name: flexi_fonts
description: "A Flutter package for dynamically changing app fonts at runtime with Google Fonts integration and persistence."
version: 0.1.0
homepage: https://github.com/Mhamad98/flexi_fonts
repository: https://github.com/Mhamad98/flexi_fonts
issue_tracker: https://github.com/Mhamad98/flexi_fonts/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700

# Additional information for pub.dev
topics:
  - fonts
  - google-fonts
  - theme
  - customization
  - accessibility
